# Generated by Django 2.1 on 2019-07-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(default='N/A', max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('scopus_author_id', models.IntegerField(default=0)),
                ('staff_member', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Authored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_reader.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('start_page', models.IntegerField(null=True)),
                ('end_page', models.IntegerField(null=True)),
                ('doi', models.TextField(blank=True, max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='N/A', max_length=30)),
                ('description', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('year_published', models.IntegerField(default=2019)),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_reader.PType')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_reader.Source'),
        ),
        migrations.AddField(
            model_name='authored',
            name='p_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_reader.Paper'),
        ),
    ]
